---
abstract: 'Wrapper for Perinci Riap clients'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Module::Build: 0.3601
  Perinci::Examples: 0
  Test::More: 0.96
  Test::Script: 1.05
  blib: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Access
requires:
  Log::Any: 0
  Perinci::Access::HTTP::Client: 0.10
  Perinci::Access::InProcess: 0.40
  Perinci::Access::Simple::Client: 0.13
  URI::Split: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Perinci-Access
  repository: http://github.com/sharyanto/perl-Perinci-Access
version: 0.35
